"""
Nodes package for ComfyUI-HMT-Suite
"""

from .model_downloader import NODE_CLASS_MAPPINGS as MODEL_DOWNLOADER_MAPPINGS
from .model_downloader import NODE_DISPLAY_NAME_MAPPINGS as MODEL_DOWNLOADER_DISPLAY_MAPPINGS

from .custom_node_installer import NODE_CLASS_MAPPINGS as CUSTOM_NODE_INSTALLER_MAPPINGS
from .custom_node_installer import NODE_DISPLAY_NAME_MAPPINGS as CUSTOM_NODE_INSTALLER_DISPLAY_MAPPINGS

from .comfyui_restart import NODE_CLASS_MAPPINGS as COMFYUI_RESTART_MAPPINGS
from .comfyui_restart import NODE_DISPLAY_NAME_MAPPINGS as COMFYUI_RESTART_DISPLAY_MAPPINGS

from .komfy import NODE_CLASS_MAPPINGS as KOMFY_MAPPINGS
from .komfy import NODE_DISPLAY_NAME_MAPPINGS as KOMFY_DISPLAY_MAPPINGS

# Merge all node mappings
NODE_CLASS_MAPPINGS = {
    **MODEL_DOWNLOADER_MAPPINGS,
    **CUSTOM_NODE_INSTALLER_MAPPINGS,
    **COMFYUI_RESTART_MAPPINGS,
    **KOMFY_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MODEL_DOWNLOADER_DISPLAY_MAPPINGS,
    **CUSTOM_NODE_INSTALLER_DISPLAY_MAPPINGS,
    **COMFYUI_RESTART_DISPLAY_MAPPINGS,
    **KOMFY_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
